/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.DesktopPaneUI;

/**
 *
 * @author Luiz Guilherme
 */
public class Principal_aluno extends javax.swing.JFrame {

    /**
     * Creates new form Quizz
     */
    public Principal_aluno() {
        initComponents();
        this.setVisible(true);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.getContentPane().setBackground(Color.white);
        pnl_principal.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        pnl_principal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mni_start = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        mni_sair = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnl_principalLayout = new javax.swing.GroupLayout(pnl_principal);
        pnl_principal.setLayout(pnl_principalLayout);
        pnl_principalLayout.setHorizontalGroup(
            pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnl_principalLayout.setVerticalGroup(
            pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mni_start.setText("Começar o Quiz");
        mni_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mni_startMouseClicked(evt);
            }
        });
        mni_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_startActionPerformed(evt);
            }
        });
        jMenuBar1.add(mni_start);

        jMenu1.setText("Voltar ao menu");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        mni_sair.setText("Sair");
        mni_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mni_sairMouseClicked(evt);
            }
        });
        mni_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_sairActionPerformed(evt);
            }
        });
        jMenuBar1.add(mni_sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mni_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_startActionPerformed
        
    }//GEN-LAST:event_mni_startActionPerformed

    private void mni_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_sairActionPerformed
           
    }//GEN-LAST:event_mni_sairActionPerformed

    private void mni_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mni_sairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_mni_sairMouseClicked

    private void mni_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mni_startMouseClicked
        QuizzView quizz;
        try {
            quizz = new QuizzView();
            pnl_principal.removeAll();
            pnl_principal.add(quizz);
            quizz.setLocation(pnl_principal.getWidth()/2 - quizz.getWidth()/2,
                    pnl_principal.getHeight()/2 - quizz.getHeight()/2);
            
            pnl_principal.updateUI();
        } catch (SQLException ex) {
            Logger.getLogger(Principal_aluno.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_mni_startMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
       MenuView menu = new MenuView();
       menu.show();
       this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mni_sair;
    private javax.swing.JMenu mni_start;
    private javax.swing.JPanel pnl_principal;
    // End of variables declaration//GEN-END:variables
}
