
package View;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Luiz Guilherme
 */
public class Principal_prof extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal_prof() {
        initComponents();
        this.setVisible(true);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelprincipal = new javax.swing.JPanel();
        menu = new javax.swing.JMenuBar();
        menu_arquivo = new javax.swing.JMenu();
        mni_cadastro = new javax.swing.JMenuItem();
        mni_quizz = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menu_sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout painelprincipalLayout = new javax.swing.GroupLayout(painelprincipal);
        painelprincipal.setLayout(painelprincipalLayout);
        painelprincipalLayout.setHorizontalGroup(
            painelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        painelprincipalLayout.setVerticalGroup(
            painelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        menu_arquivo.setText("Arquivo");
        menu_arquivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_arquivoMouseClicked(evt);
            }
        });

        mni_cadastro.setText("Cadastro de Perguntas e Respostas");
        mni_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_cadastroActionPerformed(evt);
            }
        });
        menu_arquivo.add(mni_cadastro);

        mni_quizz.setText("Quizz");
        mni_quizz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_quizzActionPerformed(evt);
            }
        });
        menu_arquivo.add(mni_quizz);

        menu.add(menu_arquivo);

        jMenu1.setText("Voltar ao Menu");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        menu.add(jMenu1);

        menu_sair.setText("Sair");
        menu_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_sairMouseClicked(evt);
            }
        });
        menu.add(menu_sair);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelprincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_sairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menu_sairMouseClicked

    private void menu_arquivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_arquivoMouseClicked
    
    }//GEN-LAST:event_menu_arquivoMouseClicked

    private void mni_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_cadastroActionPerformed
    try {
        PerguntaView perguntas = new PerguntaView();

        painelprincipal.removeAll();
        painelprincipal.add(perguntas);
        perguntas.setLocation(painelprincipal.getWidth()/2 - perguntas.getWidth()/2,
                    painelprincipal.getHeight()/2 - perguntas.getHeight()/2);
        painelprincipal.updateUI();
    } catch (SQLException ex) {
        Logger.getLogger(Principal_prof.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_mni_cadastroActionPerformed

    private void mni_quizzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_quizzActionPerformed
           QuizzView quizz;
        try {
            quizz = new QuizzView();
            painelprincipal.removeAll();
           painelprincipal.add(quizz);
           quizz.setLocation(painelprincipal.getWidth()/2 - quizz.getWidth()/2,
                    painelprincipal.getHeight()/2 - quizz.getHeight()/2);
           painelprincipal.updateUI();
        } catch (SQLException ex) {
            Logger.getLogger(Principal_prof.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_mni_quizzActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        MenuView menu = new MenuView();
        menu.show();
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menu_arquivo;
    private javax.swing.JMenu menu_sair;
    private javax.swing.JMenuItem mni_cadastro;
    private javax.swing.JMenuItem mni_quizz;
    private javax.swing.JPanel painelprincipal;
    // End of variables declaration//GEN-END:variables
}
