package View;

import DAO.PerguntaDAO;
import DAO.RespostaDAO;
import Model.Pergunta;
import Model.Resposta;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luiz Guilherme
 */
public class QuizzView extends javax.swing.JInternalFrame {
    PerguntaDAO perguntadao;
    RespostaDAO respostadao;
    List<Pergunta> listaPergunta;
    List<Resposta> listaResposta;
    int contador = 0;
    
    
    public QuizzView() throws SQLException {
        initComponents();
        this.setVisible(true);
        perguntadao = new PerguntaDAO();
        respostadao = new RespostaDAO();
        listaPergunta = perguntadao.ListaPergunta();
        lbl_idperg.setText(String.valueOf(listaPergunta.get(contador).getId()));
        lbl_descpergunta.setText(listaPergunta.get(contador).getDescricao());
        listaResposta = respostadao.ListaResposta(listaPergunta.get(contador).getId());
        rd_resp1.setText(listaResposta.get(0).getDescricao());
        rd_resp2.setText(listaResposta.get(1).getDescricao());
        rd_resp3.setText(listaResposta.get(2).getDescricao());
        rd_resp4.setText(listaResposta.get(3).getDescricao());
        pnl_principal.setBackground(Color.white);
        rd_resp1.setBackground(Color.white);
        rd_resp2.setBackground(Color.white);
        rd_resp3.setBackground(Color.white);
        rd_resp4.setBackground(Color.white);
        btn_proximo.setEnabled(false);
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_group = new javax.swing.ButtonGroup();
        pnl_principal = new javax.swing.JPanel();
        rd_resp4 = new javax.swing.JRadioButton();
        rd_resp3 = new javax.swing.JRadioButton();
        rd_resp2 = new javax.swing.JRadioButton();
        rd_resp1 = new javax.swing.JRadioButton();
        lbl_idperg = new javax.swing.JLabel();
        lbl_descpergunta = new javax.swing.JLabel();
        btn_verificar = new javax.swing.JButton();
        btn_proximo = new javax.swing.JButton();

        btn_group.add(rd_resp4);
        rd_resp4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_group.add(rd_resp3);
        rd_resp3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_group.add(rd_resp2);
        rd_resp2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_group.add(rd_resp1);
        rd_resp1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_idperg.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbl_idperg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbl_descpergunta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_descpergunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btn_verificar.setBackground(new java.awt.Color(115, 255, 124));
        btn_verificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_verificar.setText("Verificar Resposta");
        btn_verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verificarActionPerformed(evt);
            }
        });

        btn_proximo.setBackground(new java.awt.Color(185, 185, 244));
        btn_proximo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_proximo.setText("Proxima Pergunta");
        btn_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_principalLayout = new javax.swing.GroupLayout(pnl_principal);
        pnl_principal.setLayout(pnl_principalLayout);
        pnl_principalLayout.setHorizontalGroup(
            pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_descpergunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_idperg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_principalLayout.createSequentialGroup()
                        .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_principalLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(btn_verificar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btn_proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(rd_resp4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(rd_resp1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rd_resp2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rd_resp3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(78, Short.MAX_VALUE))))
        );
        pnl_principalLayout.setVerticalGroup(
            pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_principalLayout.createSequentialGroup()
                .addComponent(lbl_idperg, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_descpergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd_resp1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rd_resp2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rd_resp3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rd_resp4)
                .addGap(47, 47, 47)
                .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_verificar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verificarActionPerformed
      if (rd_resp1.isSelected())
      {
          if(listaPergunta.get(contador).getResposta_certa() == listaResposta.get(0).getId())
          {
              JOptionPane.showMessageDialog(null, "Parabéns você Acertou!");
              btn_proximo.setEnabled(true);
              btn_verificar.setEnabled(false);
          }
          else
          {
              JOptionPane.showMessageDialog(null, listaPergunta.get(contador).getComentario());
          }
      }
      if(rd_resp2.isSelected())
      {
          if(listaPergunta.get(contador).getResposta_certa() == listaResposta.get(1).getId())
          {
              JOptionPane.showMessageDialog(null, "Parabéns você Acertou!");
              btn_proximo.setEnabled(true);
              btn_verificar.setEnabled(false);
          }
          else
          {
              JOptionPane.showMessageDialog(null, listaPergunta.get(contador).getComentario());
          }
          
      }
      if(rd_resp3.isSelected())
      {
          if(listaPergunta.get(contador).getResposta_certa() == listaResposta.get(2).getId())
          {
              JOptionPane.showMessageDialog(null, "Parabéns você Acertou!");
              btn_proximo.setEnabled(true);
              btn_verificar.setEnabled(false);
          }
          else
          {
              JOptionPane.showMessageDialog(null, listaPergunta.get(contador).getComentario());
          }
          
      }
      if(rd_resp4.isSelected())
      {
          if(listaPergunta.get(contador).getResposta_certa() == listaResposta.get(3).getId())
          {
              JOptionPane.showMessageDialog(null, "Parabéns você Acertou!");
              btn_proximo.setEnabled(true);
              btn_verificar.setEnabled(false);
          }
          else
          {
              JOptionPane.showMessageDialog(null, listaPergunta.get(contador).getComentario());
          }
          
      }
    }//GEN-LAST:event_btn_verificarActionPerformed

   

    
    private void btn_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proximoActionPerformed
        btn_group.clearSelection();
        contador = contador + 1;
        if( listaPergunta.size()> contador)
        {
         
            try {
                lbl_idperg.setText(String.valueOf(listaPergunta.get(contador).getId()));
                lbl_descpergunta.setText(listaPergunta.get(contador).getDescricao()); 
                listaResposta = respostadao.ListaResposta(listaPergunta.get(contador).getId());
                rd_resp1.setText(listaResposta.get(0).getDescricao());
                rd_resp2.setText(listaResposta.get(1).getDescricao());
                rd_resp3.setText(listaResposta.get(2).getDescricao());
                rd_resp4.setText(listaResposta.get(3).getDescricao());
                btn_proximo.setEnabled(false);
              btn_verificar.setEnabled(true);
            } catch (SQLException ex) {
                Logger.getLogger(QuizzView.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }
        else
            {
                    JOptionPane.showMessageDialog(null, "<html>Fim das Perguntas!<br>Você acertou tudo, Parabéns!</html>");
                    //Final fim = new Final();
                    //fim.show();
                    //Principal_aluno aluno = new Principal_aluno();
                    //aluno.dispose();
            }
    }//GEN-LAST:event_btn_proximoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btn_group;
    private javax.swing.JButton btn_proximo;
    private javax.swing.JButton btn_verificar;
    private javax.swing.JLabel lbl_descpergunta;
    private javax.swing.JLabel lbl_idperg;
    private javax.swing.JPanel pnl_principal;
    private javax.swing.JRadioButton rd_resp1;
    private javax.swing.JRadioButton rd_resp2;
    private javax.swing.JRadioButton rd_resp3;
    private javax.swing.JRadioButton rd_resp4;
    // End of variables declaration//GEN-END:variables
}
